version: '3.7'
services:
    ohana-mysql:
      image: ohana-mysql
      command: mysqld --default-authentication-plugin=mysql_native_password
      restart: always
      build: ../../mysql
      container_name: ohana-mysql
      environment:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: ohana
      ports:
        - "3306:3306"
